application: participantseditor
version: 1
runtime: python
api_version: 1

handlers:
    - url: /media/js
      static_dir: media/js
      
    - url: /media/css
      static_dir: media/css

    - url: /media/images
      static_dir: media/images

    - url: /media/others
      static_dir: media/others

    - url: .*
      script: main.py
